### ISSUE TITLE
Question about uploading a file to moodle

### ISSUE THREAD

**Issue by arieljannai** [ltalirz/moodle-qformat_qtex#1]
HI,

Sorry I'm asking it over here even that it's not related, but I came across [your script](https://github.com/ltalirz/moodle-qformat_qtex/blob/master/moodle-converter/moodle_question_converter.sh) and wanted to know if maybe you know how to submit an assignment with the file I just uploaded.
I edited your script so I'll upload the file, but I don't seem to get it to how to assign it to my submission.
[This](https://gist.github.com/arieljannai/650f6a918fe82a333404ff4ef53bb065) is how my edit looks like

Thank in advance if you know how to guide me!

**Comment by ltalirz** [comment]
Hi @arieljannai , could you please elaborate a bit on what you are trying to do?
It's quite some time since I worked on the Moodle plugin.

**Comment by arieljannai** [comment]
Hi!

I want to create a script that will submit an assignment for me in one of the courses I have in the moodle. It can be a `pdf`, `zip` or another type.
What I currently achieved after editing your script is the url of the file I uploaded (with your script).
But now, I'm trying to understand how I can use the file in the link, which is already in our moodle, and use it to submit my assignment.
For example, this is a file I've uploaded manually:
![image](https://cloud.githubusercontent.com/assets/3811594/23998040/787b24a2-0a5c-11e7-8cc2-12ef3a61a58b.png).

Do you know if I should be able to find the uploaded file (via your script) somewhere in the moodle site?

I've also tried tracking whats happening with fiddler, but I kept getting `incorrect sesskey` although it was fine.

Thanks

**Comment by ltalirz** [comment]
Ok, perhaps @patsp can help you with this as he wrote that part of the code...

**Comment by patsp** [comment]
Sorry for the late reply. I have not noticed that I was referenced here.

I installed and tested with the current Moodle version. It has changed since the initial development of the script. What you are missing in your script seems to be the part of the "Save changes" button. If that button is pressed a POST request to the `url_to_moodle/user/files.php` is sent to actually save the uploaded file from the draft into the private area if I understood it correctly.

So you could try adding something like

```bash
curl --silent --cookie $COOKIE_FILE --location \
     --data "sesskey=$sesskey" \
     --data "_qf__user_files_form=1" \
     --data "files_filemanager=$itemid" \
     --data "submitbutton=Save changes" \
     $FILES_URL
```

at the end of the script after the `upload` call and before the `logOut` call where I set `FILES_URL` like this: `FILES_URL="$argUrlToMoodle/user/files.php"`.
Of course this can be put into a function similarly to the other requests. Uploading a file with a name that already exists in the private files probably needs special handling.

**Comment by arieljannai** [comment]
Thanks a lot! I'll look into that

**Comment by ltalirz** [comment]
Closing as I assume this was fixed.
